import type { MediaType } from "@/types";

export interface CatalogSeedItem {
  slug: string;
  title: string;
  type: MediaType;
  description?: string;
  synopsis?: string;
  imageUrl?: string;
  rating?: number;
  year?: number;
  meta?: string;
  accent?: string;
  genreLabels: string[];
}

const poster = (slug: string) => `/images/posters/${slug}.jpg`;

/** Starter catalog imported from the original mock discover pool. */
export const CATALOG_SEED_ITEMS: CatalogSeedItem[] = [
  {
    slug: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    type: "anime",
    imageUrl: poster("jujutsu-kaisen"),
    genreLabels: ["Action", "Thriller"],
    rating: 9.5,
    year: 2019,
    meta: "4 Seasons",
    accent: "blue",
    description:
      "A dark action anime where cursed energy, brutal battles, and powerful sorcerers collide.",
    synopsis:
      "A boy swallows a cursed talisman and becomes the vessel of a demon. He enrolls at a shaman school to find the remaining fingers and survive a war between sorcerers and curses.",
  },
  {
    slug: "demon-slayer",
    title: "Demon Slayer",
    type: "anime",
    imageUrl: poster("demon-slayer"),
    genreLabels: ["Fantasy", "Action"],
    rating: 8.9,
    year: 2019,
    meta: "4 Seasons",
    accent: "purple",
    description: "A young boy joins the Demon Slayer Corps to save his sister.",
  },
  {
    slug: "attack-on-titan",
    title: "Attack on Titan",
    type: "anime",
    imageUrl: poster("attack-on-titan"),
    genreLabels: ["Drama", "Action"],
    rating: 9.3,
    year: 2013,
    meta: "4 Seasons",
    accent: "cyan",
    description: "Humanity fights for survival behind walls as titans threaten everything.",
  },
  {
    slug: "classroom-of-elite",
    title: "Classroom Of Elite",
    type: "anime",
    imageUrl: poster("classroom-of-the-elite"),
    genreLabels: ["Drama", "Thriller"],
    rating: 9.2,
    year: 2017,
    meta: "3 Seasons",
    accent: "yellow",
  },
  {
    slug: "chainsaw-man",
    title: "Chainsaw Man",
    type: "anime",
    imageUrl: poster("chainsaw-man"),
    genreLabels: ["Horror", "Action"],
    rating: 8.8,
    year: 2022,
    meta: "1 Season",
    accent: "pink",
  },
  {
    slug: "frieren",
    title: "Frieren",
    type: "anime",
    imageUrl: poster("frieren"),
    genreLabels: ["Fantasy", "Drama"],
    rating: 9.4,
    year: 2023,
    meta: "1 Season",
    accent: "green",
  },
  {
    slug: "spy-x-family",
    title: "Spy x Family",
    type: "anime",
    imageUrl: poster("spy-x-family"),
    genreLabels: ["Comedy", "Action"],
    rating: 8.8,
    year: 2022,
    meta: "2 Seasons",
    accent: "pink",
  },
  {
    slug: "vinland-saga",
    title: "Vinland Saga",
    type: "anime",
    imageUrl: poster("vinland-saga"),
    genreLabels: ["Drama", "Action"],
    rating: 9.1,
    year: 2019,
    meta: "2 Seasons",
    accent: "blue",
  },
  {
    slug: "your-name",
    title: "Your Name",
    type: "movie",
    imageUrl: poster("your-name"),
    genreLabels: ["Romance", "Fantasy"],
    rating: 9.1,
    year: 2016,
    meta: "Film",
    accent: "cyan",
  },
  {
    slug: "death-note",
    title: "Death Note",
    type: "anime",
    imageUrl: poster("death-note"),
    genreLabels: ["Crime", "Thriller"],
    rating: 9.2,
    year: 2006,
    meta: "1 Season",
    accent: "purple",
  },
  {
    slug: "tokyo-ghoul",
    title: "Tokyo Ghoul",
    type: "anime",
    imageUrl: poster("tokyo-ghoul"),
    genreLabels: ["Horror", "Action"],
    rating: 8.5,
    year: 2014,
    meta: "4 Seasons",
    accent: "pink",
  },
  {
    slug: "blue-lock",
    title: "Blue Lock",
    type: "anime",
    imageUrl: poster("blue-lock"),
    genreLabels: ["Sports", "Drama"],
    rating: 8.5,
    year: 2022,
    meta: "2 Seasons",
    accent: "green",
  },
  {
    slug: "haikyu",
    title: "Haikyu!!",
    type: "anime",
    imageUrl: poster("haikyu"),
    genreLabels: ["Sports", "Comedy"],
    rating: 9.1,
    year: 2014,
    meta: "4 Seasons",
    accent: "yellow",
  },
  {
    slug: "oshi-no-ko",
    title: "Oshi no Ko",
    type: "anime",
    imageUrl: poster("oshi-no-ko"),
    genreLabels: ["Drama", "Mystery"],
    rating: 8.9,
    year: 2023,
    meta: "2 Seasons",
    accent: "pink",
  },
  {
    slug: "monster",
    title: "Monster",
    type: "anime",
    imageUrl: poster("monster"),
    genreLabels: ["Crime", "Mystery"],
    rating: 9,
    year: 2004,
    meta: "1 Season",
    accent: "blue",
  },
  {
    slug: "code-geass",
    title: "Code Geass",
    type: "anime",
    imageUrl: poster("code-geass"),
    genreLabels: ["Action", "Thriller"],
    rating: 9.1,
    year: 2006,
    meta: "2 Seasons",
    accent: "purple",
  },
  {
    slug: "naruto-shippuden",
    title: "Naruto Shippuden",
    type: "anime",
    imageUrl: poster("naruto-shippuden"),
    genreLabels: ["Action", "Fantasy"],
    rating: 8.7,
    year: 2007,
    meta: "21 Seasons",
    accent: "yellow",
  },
  {
    slug: "suzume",
    title: "Suzume",
    type: "movie",
    imageUrl: poster("suzume"),
    genreLabels: ["Fantasy", "Romance"],
    rating: 8.7,
    year: 2022,
    meta: "Film",
    accent: "cyan",
  },
];
