import type { ArtistSeed } from "./helpers";
import { poster } from "./helpers";

const p = poster;

export const ARTIST_ITEMS: ArtistSeed[] = [
  {
    slug: "lisa",
    title: "LiSA",
    nativeTitle: "リサ",
    accent: "pink",
    rating: 8.8,
    rankLeft: "#3 in J-Pop",
    rankRight: "#1 in Anime OST Artists",
    genreLabels: ["jpop", "rock", "ost"],
    languages: ["japanese", "english"],
    label: "Sacra Music",
    debutYear: 2010,
    isGroup: false,
    primaryTags: ["Anime OP Queen", "Rock"],
    imageUrl: p("lisa"),
    synopsis:
      "LiSA is one of Japan's most iconic anime theme performers, known for Demon Slayer and Sword Art Online hits.",
    catalogReviews: [
      { authorName: "Reetam Dutta", rating: 9, body: "Gurenge alone puts her in the hall of fame.", accent: "pink", likeCount: 44 },
    ],
  },
  {
    slug: "yoasobi",
    title: "YOASOBI",
    accent: "blue",
    rating: 9.0,
    rankLeft: "#1 in J-Pop",
    genreLabels: ["jpop", "electronic", "ballad"],
    languages: ["japanese"],
    label: "Sony Music",
    debutYear: 2019,
    isGroup: true,
    members: [
      { name: "Ayase", role: "Composer" },
      { name: "Ikura", role: "Vocalist" },
    ],
    imageUrl: p("yoasobi"),
    synopsis:
      "YOASOBI turns novels into viral J-pop anthems — Idol and Yoru ni Kakeru defined a generation.",
    catalogReviews: [
      { authorName: "Aanya Rao", rating: 9.5, body: "Ayase's production plus Ikura's voice is unmatched.", accent: "blue", likeCount: 61 },
    ],
  },
  {
    slug: "kenshi-yonezu",
    title: "Kenshi Yonezu",
    nativeTitle: "米津玄師",
    accent: "yellow",
    rating: 9.1,
    genreLabels: ["jpop", "rock", "indie"],
    languages: ["japanese"],
    debutYear: 2013,
    isGroup: false,
    imageUrl: p("kenshi-yonezu"),
    synopsis:
      "Kenshi Yonezu blends art-pop and rock with massive anime tie-ins like Lemon and Kick Back.",
  },
  {
    slug: "aimer",
    title: "Aimer",
    accent: "violet",
    rating: 8.7,
    genreLabels: ["jpop", "ballad", "ost"],
    languages: ["japanese", "english"],
    debutYear: 2011,
    isGroup: false,
    imageUrl: p("aimer"),
    synopsis:
      "Aimer's husky vocals define Fate, Demon Slayer movie themes, and countless emotional ballads.",
  },
  {
    slug: "radwimps",
    title: "RADWIMPS",
    accent: "cyan",
    rating: 8.9,
    genreLabels: ["rock", "jpop", "indie"],
    languages: ["japanese", "english"],
    debutYear: 2001,
    isGroup: true,
    members: [
      { name: "Yojiro Noda", role: "Vocalist" },
      { name: "Haruomi Hosono", role: "Guitar" },
      { name: "Kei Asanuma", role: "Bass" },
    ],
    imageUrl: p("radwimps"),
    synopsis:
      "RADWIMPS soundtracked Makoto Shinkai's biggest films — Your Name and Weathering With You.",
  },
  {
    slug: "eve",
    title: "Eve",
    accent: "purple",
    rating: 8.5,
    genreLabels: ["jpop", "rock", "indie"],
    languages: ["japanese"],
    debutYear: 2009,
    isGroup: false,
    imageUrl: p("eve"),
    synopsis:
      "Eve's cinematic J-pop pairs with stunning MVs — Kaikai Kitan defined the Jujutsu Kaisen era.",
  },
  {
    slug: "ado",
    title: "Ado",
    accent: "red",
    rating: 8.6,
    genreLabels: ["jpop", "rock", "electronic"],
    languages: ["japanese"],
    debutYear: 2020,
    isGroup: false,
    imageUrl: p("ado"),
    synopsis:
      "Ado burst onto the scene with explosive vocals and One Piece Film Red anthems.",
  },
  {
    slug: "king-gnu",
    title: "King Gnu",
    accent: "indigo",
    rating: 8.8,
    genreLabels: ["rock", "jpop", "electronic"],
    languages: ["japanese", "english"],
    debutYear: 2013,
    isGroup: true,
    members: [
      { name: "Tsuneda", role: "Vocalist" },
      { name: "Satoru Iguchi", role: "Guitar" },
    ],
    imageUrl: p("king-gnu"),
    synopsis:
      "King Gnu fuses rock, hip-hop, and cinematic production — Jujutsu Kaisen 0 and Spy x Family ties.",
  },
  {
    slug: "twice",
    title: "TWICE",
    nativeTitle: "트와이스",
    accent: "pink",
    rating: 8.4,
    rankLeft: "#2 in K-Pop",
    genreLabels: ["kpop", "pop", "electronic"],
    languages: ["korean", "japanese", "english"],
    label: "JYP Entertainment",
    debutYear: 2015,
    isGroup: true,
    members: [
      { name: "Nayeon", role: "Vocalist" },
      { name: "Jeongyeon", role: "Vocalist" },
      { name: "Momo", role: "Dancer" },
      { name: "Sana", role: "Vocalist" },
      { name: "Jihyo", role: "Leader" },
      { name: "Mina", role: "Dancer" },
      { name: "Dahyun", role: "Rapper" },
      { name: "Chaeyoung", role: "Rapper" },
      { name: "Tzuyu", role: "Vocalist" },
    ],
    imageUrl: p("twice"),
    synopsis:
      "TWICE is one of K-pop's biggest girl groups with chart-topping hits across Korea and Japan.",
  },
  {
    slug: "flow",
    title: "FLOW",
    accent: "orange",
    rating: 8.2,
    genreLabels: ["rock", "jpop", "ost"],
    languages: ["japanese"],
    debutYear: 1998,
    isGroup: true,
    members: [
      { name: "Koshi Asano", role: "Vocalist" },
      { name: "Gotaro", role: "Guitar" },
    ],
    imageUrl: p("flow"),
    synopsis:
      "FLOW's Sign and Colors defined Naruto Shippuden for millions of fans worldwide.",
  },
];
