import type { ContentGenre } from "@/lib/catalog-enums";
import { poster, type ContentSeedBase } from "./helpers";

const p = poster;

/** Base catalog — ~35 titles across anime, movies, K-drama, and shows. */
export const CONTENT_ITEMS: ContentSeedBase[] = [
  {
    slug: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    nativeTitle: "呪術廻戦",
    type: "anime",
    accent: "blue",
    genreLabels: ["action", "supernatural", "thriller"],
    languages: ["japanese", "english"],
    rating: 8.7,
    year: 2020,
    meta: "2 Seasons",
    seasonCount: 2,
    episodeCount: 24,
    studio: "MAPPA",
    director: "Sunghoo Park",
    originalAuthor: "Gege Akutami",
    sourceMaterial: "Manga",
    status: "Ongoing",
    ageRating: "16+",
    imdbRating: 8.5,
    malScore: 8.6,
    airedFrom: "Oct 2020",
    episodeDuration: "24 Min",
    trendingLabel: "Trending on AniVerse · ANIME",
    imageUrl: p("jujutsu-kaisen"),
    synopsis:
      "A boy swallows a cursed talisman and becomes the vessel of Sukuna. He enrolls at Tokyo Jujutsu High to fight curses alongside Megumi and Nobara.",
  },
  {
    slug: "demon-slayer",
    title: "Demon Slayer",
    nativeTitle: "鬼滅の刃",
    type: "anime",
    accent: "purple",
    genreLabels: ["action", "fantasy", "supernatural"],
    languages: ["japanese", "english"],
    rating: 8.7,
    year: 2019,
    meta: "4 Seasons",
    seasonCount: 4,
    episodeCount: 44,
    studio: "ufotable",
    director: "Haruo Sotozaki",
    originalAuthor: "Koyoharu Gotouge",
    sourceMaterial: "Manga",
    status: "Completed",
    ageRating: "16+",
    malScore: 8.7,
    airedFrom: "Apr 2019",
    episodeDuration: "24 Min",
    imageUrl: p("demon-slayer"),
    synopsis:
      "Tanjiro joins the Demon Slayer Corps to turn his sister Nezuko back into a human and avenge his family.",
  },
  {
    slug: "attack-on-titan",
    title: "Attack on Titan",
    nativeTitle: "進撃の巨人",
    type: "anime",
    accent: "cyan",
    genreLabels: ["action", "drama", "thriller"],
    languages: ["japanese", "english"],
    rating: 9.1,
    year: 2013,
    meta: "4 Seasons",
    seasonCount: 4,
    episodeCount: 87,
    studio: "MAPPA",
    director: "Yuichiro Hayashi",
    originalAuthor: "Hajime Isayama",
    status: "Completed",
    malScore: 9.1,
    airedFrom: "Apr 2013",
    airedTo: "Nov 2023",
    imageUrl: p("attack-on-titan"),
    synopsis:
      "Humanity fights for survival behind walls as titans threaten everything Eren Yeager thought he knew.",
  },
  {
    slug: "chainsaw-man",
    title: "Chainsaw Man",
    nativeTitle: "チェンソーマン",
    type: "anime",
    accent: "pink",
    genreLabels: ["action", "horror", "supernatural"],
    languages: ["japanese", "english"],
    rating: 8.5,
    year: 2022,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 12,
    studio: "MAPPA",
    director: "Ryu Nakayama",
    originalAuthor: "Tatsuki Fujimoto",
    status: "Ongoing",
    imageUrl: p("chainsaw-man"),
    synopsis:
      "Denji merges with his chainsaw devil Pochita and joins Public Safety to fight devils for a normal life.",
  },
  {
    slug: "frieren",
    title: "Frieren: Beyond Journey's End",
    nativeTitle: "葬送のフリーレン",
    type: "anime",
    accent: "green",
    genreLabels: ["adventure", "drama", "fantasy"],
    languages: ["japanese", "english"],
    rating: 9.4,
    year: 2023,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 28,
    studio: "Madhouse",
    director: "Keiichiro Sato",
    originalAuthor: "Kanehito Yamada",
    status: "Ongoing",
    malScore: 9.3,
    imageUrl: p("frieren"),
    synopsis:
      "An elven mage journeys to understand humans after her party defeats the Demon King.",
  },
  {
    slug: "spy-x-family",
    title: "Spy x Family",
    nativeTitle: "スパイファミリー",
    type: "anime",
    accent: "rose",
    genreLabels: ["action", "comedy", "slice-of-life"],
    languages: ["japanese", "english"],
    rating: 8.6,
    year: 2022,
    meta: "2 Seasons",
    seasonCount: 2,
    episodeCount: 25,
    studio: "WIT Studio / CloverWorks",
    originalAuthor: "Tatsuya Endo",
    status: "Ongoing",
    imageUrl: p("spy-x-family"),
    synopsis:
      "A spy, assassin, and telepath form a fake family — each hiding secrets from the others.",
  },
  {
    slug: "vinland-saga",
    title: "Vinland Saga",
    nativeTitle: "ヴィンランド・サガ",
    type: "anime",
    accent: "indigo",
    genreLabels: ["action", "adventure", "drama"],
    languages: ["japanese", "english"],
    rating: 8.8,
    year: 2019,
    meta: "2 Seasons",
    seasonCount: 2,
    episodeCount: 48,
    studio: "WIT Studio / MAPPA",
    originalAuthor: "Makoto Yukimura",
    status: "Ongoing",
    imageUrl: p("vinland-saga"),
    synopsis:
      "Thorfinn seeks revenge in the Viking age, then searches for a peaceful land called Vinland.",
  },
  {
    slug: "death-note",
    title: "Death Note",
    nativeTitle: "デスノート",
    type: "anime",
    accent: "violet",
    genreLabels: ["crime", "mystery", "thriller"],
    languages: ["japanese", "english"],
    rating: 8.6,
    year: 2006,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 37,
    studio: "Madhouse",
    director: "Tetsuro Araki",
    originalAuthor: "Tsugumi Ohba",
    status: "Completed",
    imageUrl: p("death-note"),
    synopsis:
      "Light Yagami finds a notebook that kills anyone whose name is written in it.",
  },
  {
    slug: "one-piece",
    title: "One Piece",
    nativeTitle: "ワンピース",
    type: "anime",
    accent: "orange",
    genreLabels: ["action", "adventure", "comedy"],
    languages: ["japanese", "english"],
    rating: 8.7,
    year: 1999,
    meta: "20+ Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Toei Animation",
    originalAuthor: "Eiichiro Oda",
    status: "Ongoing",
    imageUrl: p("one-piece"),
    synopsis:
      "Monkey D. Luffy sails the Grand Line with his crew to find the legendary One Piece treasure.",
  },
  {
    slug: "my-hero-academia",
    title: "My Hero Academia",
    nativeTitle: "僕のヒーローアカデミア",
    type: "anime",
    accent: "green",
    genreLabels: ["action", "supernatural", "sports"],
    languages: ["japanese", "english"],
    rating: 8.0,
    year: 2016,
    meta: "7 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Bones",
    originalAuthor: "Kohei Horikoshi",
    status: "Ongoing",
    imageUrl: p("my-hero-academia"),
    synopsis:
      "Quirkless Izuku Midoriya inherits One For All and trains at U.A. High to become the greatest hero.",
  },
  {
    slug: "solo-leveling",
    title: "Solo Leveling",
    nativeTitle: "俺だけレベルアップな件",
    type: "anime",
    accent: "sky",
    genreLabels: ["action", "fantasy", "adventure"],
    languages: ["japanese", "english", "korean"],
    rating: 8.4,
    year: 2024,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 12,
    studio: "A-1 Pictures",
    status: "Ongoing",
    imageUrl: p("solo-leveling"),
    synopsis:
      "Sung Jinwoo rises from the weakest hunter to an unstoppable force in a world of gates and monsters.",
  },
  {
    slug: "dungeon-meshi",
    title: "Delicious in Dungeon",
    nativeTitle: "ダンジョン飯",
    type: "anime",
    accent: "amber",
    genreLabels: ["adventure", "comedy", "fantasy"],
    languages: ["japanese", "english"],
    rating: 8.6,
    year: 2024,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Trigger",
    status: "Completed",
    imageUrl: p("dungeon-meshi"),
    synopsis:
      "Adventurers cook monsters while delving deeper to rescue a friend from a red dragon.",
  },
  {
    slug: "haikyu",
    title: "Haikyu!!",
    nativeTitle: "ハイキュー!!",
    type: "anime",
    accent: "yellow",
    genreLabels: ["sports", "comedy", "drama"],
    languages: ["japanese", "english"],
    rating: 8.7,
    year: 2014,
    meta: "4 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Production I.G",
    status: "Completed",
    imageUrl: p("haikyu"),
    synopsis:
      "Short-statured Hinata Shoyo chases volleyball greatness at Karasuno High.",
  },
  {
    slug: "blue-lock",
    title: "Blue Lock",
    nativeTitle: "ブルーロック",
    type: "anime",
    accent: "teal",
    genreLabels: ["sports", "drama", "psychological"],
    languages: ["japanese", "english"],
    rating: 8.2,
    year: 2022,
    meta: "2 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "8bit",
    status: "Ongoing",
    imageUrl: p("blue-lock"),
    synopsis:
      "Three hundred strikers compete in a ruthless program to forge Japan's ultimate egotist forward.",
  },
  {
    slug: "oshi-no-ko",
    title: "Oshi no Ko",
    nativeTitle: "【推しの子】",
    type: "anime",
    accent: "fuchsia",
    genreLabels: ["drama", "mystery", "supernatural"],
    languages: ["japanese", "english"],
    rating: 8.6,
    year: 2023,
    meta: "2 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Doga Kobo",
    status: "Ongoing",
    imageUrl: p("oshi-no-ko"),
    synopsis:
      "A doctor reincarnated as the son of an idol navigates the dark entertainment industry.",
  },
  {
    slug: "classroom-of-elite",
    title: "Classroom of the Elite",
    nativeTitle: "ようこそ実力至上主義の教室へ",
    type: "anime",
    accent: "lime",
    genreLabels: ["drama", "psychological", "thriller"],
    languages: ["japanese", "english"],
    rating: 8.0,
    year: 2017,
    meta: "3 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Lerche",
    status: "Ongoing",
    imageUrl: p("classroom-of-the-elite"),
    synopsis:
      "Kiyotaka Ayanokoji manipulates events from the shadows at an elite high school.",
  },
  {
    slug: "tokyo-ghoul",
    title: "Tokyo Ghoul",
    nativeTitle: "東京喰種",
    type: "anime",
    accent: "red",
    genreLabels: ["horror", "action", "psychological"],
    languages: ["japanese", "english"],
    rating: 7.8,
    year: 2014,
    meta: "4 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Pierrot",
    status: "Completed",
    imageUrl: p("tokyo-ghoul"),
    synopsis:
      "Ken Kaneki becomes half-ghoul and struggles to survive between two worlds.",
  },
  {
    slug: "code-geass",
    title: "Code Geass",
    nativeTitle: "コードギアス",
    type: "anime",
    accent: "purple",
    genreLabels: ["action", "sci-fi", "thriller"],
    languages: ["japanese", "english"],
    rating: 8.7,
    year: 2006,
    meta: "2 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Sunrise",
    status: "Completed",
    imageUrl: p("code-geass"),
    synopsis:
      "Lelouch vi Britannia gains the power of Geass and leads a rebellion against the empire.",
  },
  {
    slug: "naruto-shippuden",
    title: "Naruto Shippuden",
    nativeTitle: "ナルト 疾風伝",
    type: "anime",
    accent: "orange",
    genreLabels: ["action", "adventure", "fantasy"],
    languages: ["japanese", "english"],
    rating: 8.3,
    year: 2007,
    meta: "21 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Pierrot",
    status: "Completed",
    imageUrl: p("naruto-shippuden"),
    synopsis:
      "Naruto Uzumaki returns to the Hidden Leaf stronger, seeking to save Sasuke and protect the world.",
  },
  {
    slug: "steins-gate",
    title: "Steins;Gate",
    nativeTitle: "シュタインズ・ゲート",
    type: "anime",
    accent: "cyan",
    genreLabels: ["sci-fi", "thriller", "drama"],
    languages: ["japanese", "english"],
    rating: 9.1,
    year: 2011,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 12,
    studio: "White Fox",
    status: "Completed",
    imageUrl: p("steins-gate"),
    synopsis:
      "Okabe Rintaro accidentally creates a time machine and must fix a devastated timeline.",
  },
  {
    slug: "mob-psycho-100",
    title: "Mob Psycho 100",
    nativeTitle: "モブサイコ100",
    type: "anime",
    accent: "lime",
    genreLabels: ["action", "comedy", "supernatural"],
    languages: ["japanese", "english"],
    rating: 8.5,
    year: 2016,
    meta: "3 Seasons",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Bones",
    status: "Completed",
    imageUrl: p("mob-psycho-100"),
    synopsis:
      "Shigeo Kageyama suppresses his psychic powers while learning to live as an ordinary middle-schooler.",
  },
  {
    slug: "cyberpunk-edgerunners",
    title: "Cyberpunk: Edgerunners",
    type: "anime",
    accent: "pink",
    genreLabels: ["action", "sci-fi", "thriller"],
    languages: ["japanese", "english"],
    rating: 8.6,
    year: 2022,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 10,
    studio: "Trigger",
    status: "Completed",
    imageUrl: p("cyberpunk-edgerunners"),
    synopsis:
      "Street kid David joins a crew of edgerunners in Night City, chasing chrome-fueled dreams.",
  },
  {
    slug: "suzume",
    title: "Suzume",
    nativeTitle: "すずめの戸締まり",
    type: "movie",
    accent: "cyan",
    genreLabels: ["adventure", "fantasy", "supernatural"],
    languages: ["japanese", "english"],
    rating: 8.7,
    year: 2022,
    meta: "Film",
    studio: "CoMix Wave Films",
    director: "Makoto Shinkai",
    originalAuthor: "Makoto Shinkai",
    status: "Completed",
    ageRating: "13+",
    imdbRating: 7.9,
    malScore: 8.4,
    airedFrom: "Nov 2022",
    episodeDuration: "122 Min",
    imageUrl: p("suzume"),
    synopsis:
      "Suzume Iwato joins Souta Munakata on a journey across Japan to close doors releasing disasters.",
  },
  {
    slug: "your-name",
    title: "Your Name",
    nativeTitle: "君の名は。",
    type: "movie",
    accent: "sky",
    genreLabels: ["romance", "fantasy", "drama"],
    languages: ["japanese", "english"],
    rating: 8.4,
    year: 2016,
    meta: "Film",
    studio: "CoMix Wave Films",
    director: "Makoto Shinkai",
    status: "Completed",
    episodeDuration: "106 Min",
    imageUrl: p("your-name"),
    synopsis:
      "Two teenagers mysteriously swap bodies and search for each other across time and distance.",
  },
  {
    slug: "weathering-with-you",
    title: "Weathering With You",
    nativeTitle: "天気の子",
    type: "movie",
    accent: "blue",
    genreLabels: ["romance", "fantasy", "drama"],
    languages: ["japanese", "english"],
    rating: 8.0,
    year: 2019,
    meta: "Film",
    studio: "CoMix Wave Films",
    director: "Makoto Shinkai",
    episodeDuration: "112 Min",
    imageUrl: p("weathering-with-you"),
    synopsis:
      "A runaway boy meets a girl who can control the weather in a rain-soaked Tokyo.",
  },
  {
    slug: "spirited-away",
    title: "Spirited Away",
    nativeTitle: "千と千尋の神隠し",
    type: "movie",
    accent: "emerald",
    genreLabels: ["adventure", "fantasy", "supernatural"],
    languages: ["japanese", "english"],
    rating: 8.6,
    year: 2001,
    meta: "Film",
    studio: "Studio Ghibli",
    director: "Hayao Miyazaki",
    episodeDuration: "125 Min",
    imageUrl: p("spirited-away"),
    synopsis:
      "Chihiro enters a spirit world and must work at a bathhouse to save her parents.",
  },
  {
    slug: "a-silent-voice",
    title: "A Silent Voice",
    nativeTitle: "聲の形",
    type: "movie",
    accent: "rose",
    genreLabels: ["drama", "slice-of-life", "psychological"],
    languages: ["japanese", "english"],
    rating: 8.9,
    year: 2016,
    meta: "Film",
    studio: "Kyoto Animation",
    director: "Naoko Yamada",
    episodeDuration: "130 Min",
    imageUrl: p("a-silent-voice"),
    synopsis:
      "A former bully seeks redemption by reconnecting with the deaf girl he tormented.",
  },
  {
    slug: "crash-landing-on-you",
    title: "Crash Landing on You",
    nativeTitle: "사랑의 불시착",
    type: "kdrama",
    accent: "pink",
    genreLabels: ["romance", "comedy", "drama"],
    languages: ["korean", "english"],
    rating: 8.7,
    year: 2019,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 16,
    studio: "Studio Dragon",
    status: "Completed",
    episodeDuration: "70 Min",
    imageUrl: p("crash-landing-on-you"),
    synopsis:
      "A South Korean heiress crash-lands in North Korea and falls for an army officer who protects her.",
  },
  {
    slug: "squid-game",
    title: "Squid Game",
    nativeTitle: "오징어 게임",
    type: "kdrama",
    accent: "red",
    genreLabels: ["thriller", "drama", "crime"],
    languages: ["korean", "english"],
    rating: 8.0,
    year: 2021,
    meta: "2 Seasons",
    seasonCount: 1,
    episodeCount: 9,
    studio: "Siren Pictures",
    status: "Completed",
    episodeDuration: "55 Min",
    imageUrl: p("squid-game"),
    synopsis:
      "Desperate contestants play deadly children's games for a life-changing cash prize.",
  },
  {
    slug: "extraordinary-attorney-woo",
    title: "Extraordinary Attorney Woo",
    nativeTitle: "이상한 변호사 우영우",
    type: "kdrama",
    accent: "teal",
    genreLabels: ["drama", "comedy", "slice-of-life"],
    languages: ["korean", "english"],
    rating: 8.8,
    year: 2022,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 16,
    status: "Completed",
    imageUrl: p("extraordinary-attorney-woo"),
    synopsis:
      "A brilliant autistic lawyer navigates courtrooms and office politics with whale-like passion.",
  },
  {
    slug: "arcane",
    title: "Arcane",
    type: "show",
    accent: "violet",
    genreLabels: ["action", "fantasy", "drama"],
    languages: ["english"],
    rating: 9.0,
    year: 2021,
    meta: "2 Seasons",
    seasonCount: 2,
    episodeCount: 18,
    studio: "Fortiche Production",
    status: "Ongoing",
    episodeDuration: "40 Min",
    imageUrl: p("arcane"),
    synopsis:
      "Sisters Vi and Jinx are torn apart on opposite sides of Piltover and Zaun's rising conflict.",
  },
  {
    slug: "the-last-of-us",
    title: "The Last of Us",
    type: "show",
    accent: "green",
    genreLabels: ["drama", "thriller", "sci-fi"],
    languages: ["english"],
    rating: 8.8,
    year: 2023,
    meta: "2 Seasons",
    seasonCount: 1,
    episodeCount: 9,
    studio: "HBO",
    status: "Ongoing",
    episodeDuration: "55 Min",
    imageUrl: p("the-last-of-us"),
    synopsis:
      "Joel escorts Ellie across a post-apocalyptic America ravaged by a fungal pandemic.",
  },
  {
    slug: "planet-earth",
    title: "Planet Earth II",
    type: "documentary",
    accent: "emerald",
    genreLabels: ["adventure", "drama"],
    languages: ["english"],
    rating: 9.5,
    year: 2016,
    meta: "Documentary",
    studio: "BBC",
    director: "Elizabeth White",
    status: "Completed",
    episodeDuration: "50 Min",
    imageUrl: p("planet-earth"),
    synopsis:
      "Stunning wildlife cinematography explores islands, mountains, jungles, and cities across Earth.",
  },
  {
    slug: "monster",
    title: "Monster",
    nativeTitle: "モンスター",
    type: "anime",
    accent: "indigo",
    genreLabels: ["crime", "mystery", "psychological"],
    languages: ["japanese", "english", "german"],
    rating: 8.9,
    year: 2004,
    meta: "1 Season",
    seasonCount: 1,
    episodeCount: 12,
    studio: "Madhouse",
    director: "Naoki Urasawa",
    status: "Completed",
    imageUrl: p("monster"),
    synopsis:
      "Dr. Tenma hunts his former patient Johan, a charismatic killer shaping Europe's shadows.",
  },
];
