import type { MusicSeed } from "./helpers";
import { poster } from "./helpers";

const p = poster;

export const MUSIC_ITEMS: MusicSeed[] = [
  {
    slug: "gurenge",
    title: "Gurenge",
    artist: "LiSA",
    artistSlug: "lisa",
    kind: "ost",
    contentSlug: "demon-slayer",
    source: "Demon Slayer",
    language: "japanese",
    genreLabels: ["ost", "rock", "jpop"],
    rating: 9.2,
    year: 2019,
    durationLabel: "3:58",
    durationSeconds: 238,
    accent: "purple",
    imageUrl: p("gurenge"),
    trendingLabel: "Trending on AniVerse · OST",
    creditLabel: "By LiSA",
    featuredRank: 1,
    description: "The explosive opening theme that launched Demon Slayer into global phenomenon status.",
    catalogReviews: [
      { authorName: "Reetam Dutta", rating: 9.5, body: "Instant goosebumps every time. Peak anime OP.", accent: "purple", likeCount: 89 },
    ],
  },
  {
    slug: "kaikai-kitan",
    title: "Kaikai Kitan",
    artist: "Eve",
    artistSlug: "eve",
    kind: "ost",
    contentSlug: "jujutsu-kaisen",
    source: "Jujutsu Kaisen",
    language: "japanese",
    genreLabels: ["ost", "jpop", "rock"],
    rating: 9.0,
    year: 2020,
    durationLabel: "3:40",
    durationSeconds: 220,
    accent: "blue",
    imageUrl: p("kaikai-kitan"),
    featuredRank: 1,
    description: "Jujutsu Kaisen season 1 opening — dark, stylish, and unforgettable.",
  },
  {
    slug: "idol",
    title: "Idol",
    artist: "YOASOBI",
    artistSlug: "yoasobi",
    kind: "ost",
    contentSlug: "oshi-no-ko",
    source: "Oshi no Ko",
    language: "japanese",
    genreLabels: ["ost", "jpop", "electronic"],
    rating: 9.3,
    year: 2023,
    durationLabel: "3:33",
    durationSeconds: 213,
    accent: "fuchsia",
    imageUrl: p("idol"),
    featuredRank: 1,
    description: "YOASOBI's viral anthem capturing the glitter and darkness of idol culture.",
  },
  {
    slug: "zenzenzense",
    title: "Zenzenzense",
    artist: "RADWIMPS",
    artistSlug: "radwimps",
    kind: "ost",
    contentSlug: "your-name",
    source: "Your Name",
    language: "japanese",
    genreLabels: ["ost", "rock", "jpop"],
    rating: 9.1,
    year: 2016,
    durationLabel: "4:48",
    durationSeconds: 288,
    accent: "sky",
    imageUrl: p("zenzenzense"),
    featuredRank: 1,
  },
  {
    slug: "sparkle",
    title: "Sparkle",
    artist: "RADWIMPS",
    artistSlug: "radwimps",
    kind: "ost",
    contentSlug: "your-name",
    source: "Your Name",
    language: "japanese",
    genreLabels: ["ost", "ballad", "jpop"],
    rating: 9.4,
    year: 2016,
    durationLabel: "8:54",
    durationSeconds: 534,
    accent: "cyan",
    imageUrl: p("sparkle"),
    featuredRank: 2,
  },
  {
    slug: "kick-back",
    title: "KICK BACK",
    artist: "Kenshi Yonezu",
    artistSlug: "kenshi-yonezu",
    kind: "ost",
    contentSlug: "chainsaw-man",
    source: "Chainsaw Man",
    language: "japanese",
    genreLabels: ["ost", "rock", "jpop"],
    rating: 8.8,
    year: 2022,
    durationLabel: "3:14",
    durationSeconds: 194,
    accent: "pink",
    imageUrl: p("kick-back"),
    featuredRank: 1,
  },
  {
    slug: "shinzou-wo-sasageyo",
    title: "Shinzou wo Sasageyo!",
    artist: "Linked Horizon",
    kind: "ost",
    contentSlug: "attack-on-titan",
    source: "Attack on Titan",
    language: "japanese",
    genreLabels: ["ost", "rock", "metal"],
    rating: 9.2,
    year: 2017,
    durationLabel: "5:13",
    durationSeconds: 313,
    accent: "green",
    imageUrl: p("attack-on-titan"),
    featuredRank: 1,
  },
  {
    slug: "homura",
    title: "Homura",
    artist: "LiSA",
    artistSlug: "lisa",
    kind: "ost",
    contentSlug: "demon-slayer",
    source: "Demon Slayer: Mugen Train",
    language: "japanese",
    genreLabels: ["ost", "ballad", "jpop"],
    rating: 9.0,
    year: 2020,
    durationLabel: "4:35",
    durationSeconds: 275,
    accent: "rose",
    imageUrl: p("homura"),
    featuredRank: 2,
  },
  {
    slug: "unravel",
    title: "unravel",
    artist: "TK from Ling Tosite Sigure",
    kind: "ost",
    contentSlug: "tokyo-ghoul",
    source: "Tokyo Ghoul",
    language: "japanese",
    genreLabels: ["ost", "rock", "indie"],
    rating: 9.5,
    year: 2014,
    durationLabel: "4:00",
    durationSeconds: 240,
    accent: "red",
    imageUrl: p("tokyo-ghoul"),
    featuredRank: 1,
  },
  {
    slug: "peace-sign",
    title: "Peace Sign",
    artist: "Kenshi Yonezu",
    artistSlug: "kenshi-yonezu",
    kind: "ost",
    contentSlug: "my-hero-academia",
    source: "My Hero Academia",
    language: "japanese",
    genreLabels: ["ost", "jpop", "rock"],
    rating: 8.5,
    year: 2017,
    durationLabel: "4:00",
    durationSeconds: 240,
    accent: "green",
    imageUrl: p("peace-sign"),
  },
  {
    slug: "suzume",
    title: "Suzume",
    artist: "RADWIMPS feat. Toaka",
    artistSlug: "radwimps",
    kind: "ost",
    contentSlug: "suzume",
    source: "Suzume",
    language: "japanese",
    genreLabels: ["ost", "ballad", "jpop"],
    rating: 8.7,
    year: 2022,
    durationLabel: "3:53",
    durationSeconds: 233,
    accent: "cyan",
    imageUrl: p("suzume"),
    featuredRank: 1,
  },
  {
    slug: "sign",
    title: "Sign",
    artist: "FLOW",
    artistSlug: "flow",
    kind: "ost",
    contentSlug: "naruto-shippuden",
    source: "Naruto Shippuden",
    language: "japanese",
    genreLabels: ["ost", "rock", "jpop"],
    rating: 8.9,
    year: 2009,
    durationLabel: "3:35",
    durationSeconds: 215,
    accent: "orange",
    imageUrl: p("sign"),
    featuredRank: 1,
  },
  {
    slug: "lost-in-paradise",
    title: "LOST IN PARADISE",
    artist: "ALI feat. AKLO",
    kind: "ost",
    contentSlug: "jujutsu-kaisen",
    source: "Jujutsu Kaisen",
    language: "japanese",
    genreLabels: ["ost", "hip-hop", "jpop"],
    rating: 8.8,
    year: 2020,
    durationLabel: "3:42",
    durationSeconds: 222,
    accent: "blue",
    imageUrl: p("lost-in-paradise"),
    featuredRank: 2,
  },
  {
    slug: "first-death",
    title: "first death",
    artist: "TK from Ling Tosite Sigure",
    kind: "ost",
    contentSlug: "chainsaw-man",
    source: "Chainsaw Man",
    language: "japanese",
    genreLabels: ["ost", "rock", "indie"],
    rating: 8.6,
    year: 2022,
    durationLabel: "3:25",
    durationSeconds: 205,
    accent: "pink",
    imageUrl: p("first-death"),
    featuredRank: 2,
  },
  {
    slug: "lemon",
    title: "Lemon",
    artist: "Kenshi Yonezu",
    artistSlug: "kenshi-yonezu",
    kind: "song",
    language: "japanese",
    genreLabels: ["jpop", "ballad"],
    rating: 9.2,
    year: 2018,
    durationLabel: "4:15",
    durationSeconds: 255,
    accent: "yellow",
    imageUrl: p("lemon"),
    trendingLabel: "Trending on AniVerse · SONG",
    featuredRank: 3,
  },
  {
    slug: "usseewa",
    title: "Usseewa",
    artist: "Ado",
    artistSlug: "ado",
    kind: "song",
    language: "japanese",
    genreLabels: ["jpop", "rock"],
    rating: 8.4,
    year: 2020,
    durationLabel: "3:27",
    durationSeconds: 207,
    accent: "red",
    imageUrl: p("usseewa"),
  },
  {
    slug: "night-dancer",
    title: "Night Dancer",
    artist: "imase",
    kind: "song",
    language: "japanese",
    genreLabels: ["jpop", "electronic"],
    rating: 8.3,
    year: 2021,
    durationLabel: "3:13",
    durationSeconds: 193,
    accent: "violet",
    imageUrl: p("night-dancer"),
  },
  {
    slug: "mixed-nuts",
    title: "Mixed Nuts",
    artist: "Official HIGE DANdism",
    kind: "ost",
    contentSlug: "spy-x-family",
    source: "Spy x Family",
    language: "japanese",
    genreLabels: ["ost", "jpop", "rock"],
    rating: 8.5,
    year: 2022,
    durationLabel: "3:30",
    durationSeconds: 210,
    accent: "rose",
    imageUrl: p("mixed-nuts"),
  },
  {
    slug: "anytime-anywhere",
    title: "Anytime Anywhere",
    artist: "milet",
    kind: "ost",
    contentSlug: "frieren",
    source: "Frieren",
    language: "japanese",
    genreLabels: ["ost", "ballad", "jpop"],
    rating: 8.7,
    year: 2023,
    durationLabel: "4:32",
    durationSeconds: 272,
    accent: "green",
    imageUrl: p("anytime-anywhere"),
  },
  {
    slug: "the-real-folk-blues",
    title: "The Real Folk Blues",
    artist: "Seatbelts",
    kind: "ost",
    source: "Cowboy Bebop",
    language: "english",
    genreLabels: ["ost", "jazz", "rock"],
    rating: 9.0,
    year: 1998,
    durationLabel: "6:08",
    durationSeconds: 368,
    accent: "indigo",
    imageUrl: p("the-real-folk-blues"),
  },
  {
    slug: "fancy",
    title: "FANCY",
    artist: "TWICE",
    artistSlug: "twice",
    kind: "song",
    language: "korean",
    genreLabels: ["kpop", "pop", "electronic"],
    rating: 8.5,
    year: 2019,
    durationLabel: "3:34",
    durationSeconds: 214,
    accent: "pink",
    imageUrl: p("fancy"),
    trendingLabel: "Trending on AniVerse · K-POP",
    featuredRank: 1,
  },
  {
    slug: "cry-for-me",
    title: "Cry For Me",
    artist: "TWICE",
    artistSlug: "twice",
    kind: "song",
    language: "korean",
    genreLabels: ["kpop", "rnb"],
    rating: 8.6,
    year: 2020,
    durationLabel: "3:29",
    durationSeconds: 209,
    accent: "fuchsia",
    imageUrl: p("cry-for-me"),
    featuredRank: 2,
  },
  {
    slug: "but-not-for-me",
    title: "But Not For Me",
    artist: "King Gnu",
    artistSlug: "king-gnu",
    kind: "ost",
    contentSlug: "jujutsu-kaisen",
    source: "Jujutsu Kaisen 0",
    language: "japanese",
    genreLabels: ["ost", "rock", "jpop"],
    rating: 8.4,
    year: 2021,
    durationLabel: "4:02",
    durationSeconds: 242,
    accent: "indigo",
    imageUrl: p("but-not-for-me"),
  },
  {
    slug: "kanata-haluka",
    title: "Kanata Haluka",
    artist: "RADWIMPS",
    artistSlug: "radwimps",
    kind: "ost",
    contentSlug: "suzume",
    source: "Suzume",
    language: "japanese",
    genreLabels: ["ost", "ballad"],
    rating: 8.5,
    year: 2022,
    durationLabel: "5:40",
    durationSeconds: 340,
    accent: "sky",
    imageUrl: p("kanata-haluka"),
    featuredRank: 2,
  },
];
